# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=0.1.1-alpha
maven_group=dev.atlasmap
archives_base_name=atlasmap

# Dependencies
fabric_api_version=0.154.0+26.2

java_version=26
